version: '3.4'

services:
  vfstracker:
    image: vfstracker
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3123:3123
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
